// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: job.proto

package jobqueuev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkerEvent struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	WorkerId string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*WorkerEvent_Register
	//	*WorkerEvent_Heartbeat
	//	*WorkerEvent_JobAccepted
	//	*WorkerEvent_JobResult
	Event         isWorkerEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerEvent) Reset() {
	*x = WorkerEvent{}
	mi := &file_job_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerEvent) ProtoMessage() {}

func (x *WorkerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerEvent.ProtoReflect.Descriptor instead.
func (*WorkerEvent) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerEvent) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerEvent) GetEvent() isWorkerEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *WorkerEvent) GetRegister() *RegisterWorker {
	if x != nil {
		if x, ok := x.Event.(*WorkerEvent_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *WorkerEvent) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Event.(*WorkerEvent_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *WorkerEvent) GetJobAccepted() *JobAccepted {
	if x != nil {
		if x, ok := x.Event.(*WorkerEvent_JobAccepted); ok {
			return x.JobAccepted
		}
	}
	return nil
}

func (x *WorkerEvent) GetJobResult() *JobResult {
	if x != nil {
		if x, ok := x.Event.(*WorkerEvent_JobResult); ok {
			return x.JobResult
		}
	}
	return nil
}

type isWorkerEvent_Event interface {
	isWorkerEvent_Event()
}

type WorkerEvent_Register struct {
	Register *RegisterWorker `protobuf:"bytes,10,opt,name=register,proto3,oneof"`
}

type WorkerEvent_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,11,opt,name=heartbeat,proto3,oneof"`
}

type WorkerEvent_JobAccepted struct {
	JobAccepted *JobAccepted `protobuf:"bytes,12,opt,name=job_accepted,json=jobAccepted,proto3,oneof"`
}

type WorkerEvent_JobResult struct {
	JobResult *JobResult `protobuf:"bytes,13,opt,name=job_result,json=jobResult,proto3,oneof"`
}

func (*WorkerEvent_Register) isWorkerEvent_Event() {}

func (*WorkerEvent_Heartbeat) isWorkerEvent_Event() {}

func (*WorkerEvent_JobAccepted) isWorkerEvent_Event() {}

func (*WorkerEvent_JobResult) isWorkerEvent_Event() {}

type DispatcherCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Command:
	//
	//	*DispatcherCommand_AssignJob
	//	*DispatcherCommand_CancelJob
	Command       isDispatcherCommand_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatcherCommand) Reset() {
	*x = DispatcherCommand{}
	mi := &file_job_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatcherCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatcherCommand) ProtoMessage() {}

func (x *DispatcherCommand) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatcherCommand.ProtoReflect.Descriptor instead.
func (*DispatcherCommand) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{1}
}

func (x *DispatcherCommand) GetCommand() isDispatcherCommand_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *DispatcherCommand) GetAssignJob() *AssignJob {
	if x != nil {
		if x, ok := x.Command.(*DispatcherCommand_AssignJob); ok {
			return x.AssignJob
		}
	}
	return nil
}

func (x *DispatcherCommand) GetCancelJob() *CancelJob {
	if x != nil {
		if x, ok := x.Command.(*DispatcherCommand_CancelJob); ok {
			return x.CancelJob
		}
	}
	return nil
}

type isDispatcherCommand_Command interface {
	isDispatcherCommand_Command()
}

type DispatcherCommand_AssignJob struct {
	AssignJob *AssignJob `protobuf:"bytes,10,opt,name=assign_job,json=assignJob,proto3,oneof"`
}

type DispatcherCommand_CancelJob struct {
	CancelJob *CancelJob `protobuf:"bytes,11,opt,name=cancel_job,json=cancelJob,proto3,oneof"`
}

func (*DispatcherCommand_AssignJob) isDispatcherCommand_Command() {}

func (*DispatcherCommand_CancelJob) isDispatcherCommand_Command() {}

type RegisterWorker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Concurrency   int32                  `protobuf:"varint,1,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	Capabilities  []string               `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorker) Reset() {
	*x = RegisterWorker{}
	mi := &file_job_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorker) ProtoMessage() {}

func (x *RegisterWorker) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorker.ProtoReflect.Descriptor instead.
func (*RegisterWorker) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterWorker) GetConcurrency() int32 {
	if x != nil {
		return x.Concurrency
	}
	return 0
}

func (x *RegisterWorker) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type Heartbeat struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AvailableSlots int32                  `protobuf:"varint,1,opt,name=available_slots,json=availableSlots,proto3" json:"available_slots,omitempty"`
	RunningJobs    int32                  `protobuf:"varint,2,opt,name=running_jobs,json=runningJobs,proto3" json:"running_jobs,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_job_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{3}
}

func (x *Heartbeat) GetAvailableSlots() int32 {
	if x != nil {
		return x.AvailableSlots
	}
	return 0
}

func (x *Heartbeat) GetRunningJobs() int32 {
	if x != nil {
		return x.RunningJobs
	}
	return 0
}

type AssignJob struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobId          string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Type           string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Priority       int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	RetryCount     int32                  `protobuf:"varint,4,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	MaxRetries     int32                  `protobuf:"varint,5,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,6,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	ScheduledAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Payload        []byte                 `protobuf:"bytes,9,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AssignJob) Reset() {
	*x = AssignJob{}
	mi := &file_job_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignJob) ProtoMessage() {}

func (x *AssignJob) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignJob.ProtoReflect.Descriptor instead.
func (*AssignJob) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{4}
}

func (x *AssignJob) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *AssignJob) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AssignJob) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *AssignJob) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *AssignJob) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *AssignJob) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *AssignJob) GetScheduledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledAt
	}
	return nil
}

func (x *AssignJob) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AssignJob) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type JobAccepted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobAccepted) Reset() {
	*x = JobAccepted{}
	mi := &file_job_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobAccepted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobAccepted) ProtoMessage() {}

func (x *JobAccepted) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobAccepted.ProtoReflect.Descriptor instead.
func (*JobAccepted) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{5}
}

func (x *JobAccepted) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type JobResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Output        []byte                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobResult) Reset() {
	*x = JobResult{}
	mi := &file_job_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResult) ProtoMessage() {}

func (x *JobResult) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResult.ProtoReflect.Descriptor instead.
func (*JobResult) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{6}
}

func (x *JobResult) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *JobResult) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *JobResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type CancelJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJob) Reset() {
	*x = CancelJob{}
	mi := &file_job_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJob) ProtoMessage() {}

func (x *CancelJob) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJob.ProtoReflect.Descriptor instead.
func (*CancelJob) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{7}
}

func (x *CancelJob) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CancelJob) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_job_proto protoreflect.FileDescriptor

const file_job_proto_rawDesc = "" +
	"\n" +
	"\tjob.proto\x12\vjobqueue.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9e\x02\n" +
	"\vWorkerEvent\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x129\n" +
	"\bregister\x18\n" +
	" \x01(\v2\x1b.jobqueue.v1.RegisterWorkerH\x00R\bregister\x126\n" +
	"\theartbeat\x18\v \x01(\v2\x16.jobqueue.v1.HeartbeatH\x00R\theartbeat\x12=\n" +
	"\fjob_accepted\x18\f \x01(\v2\x18.jobqueue.v1.JobAcceptedH\x00R\vjobAccepted\x127\n" +
	"\n" +
	"job_result\x18\r \x01(\v2\x16.jobqueue.v1.JobResultH\x00R\tjobResultB\a\n" +
	"\x05event\"\x90\x01\n" +
	"\x11DispatcherCommand\x127\n" +
	"\n" +
	"assign_job\x18\n" +
	" \x01(\v2\x16.jobqueue.v1.AssignJobH\x00R\tassignJob\x127\n" +
	"\n" +
	"cancel_job\x18\v \x01(\v2\x16.jobqueue.v1.CancelJobH\x00R\tcancelJobB\t\n" +
	"\acommand\"V\n" +
	"\x0eRegisterWorker\x12 \n" +
	"\vconcurrency\x18\x01 \x01(\x05R\vconcurrency\x12\"\n" +
	"\fcapabilities\x18\x02 \x03(\tR\fcapabilities\"W\n" +
	"\tHeartbeat\x12'\n" +
	"\x0favailable_slots\x18\x01 \x01(\x05R\x0eavailableSlots\x12!\n" +
	"\frunning_jobs\x18\x02 \x01(\x05R\vrunningJobs\"\xd1\x02\n" +
	"\tAssignJob\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x12\x1f\n" +
	"\vretry_count\x18\x04 \x01(\x05R\n" +
	"retryCount\x12\x1f\n" +
	"\vmax_retries\x18\x05 \x01(\x05R\n" +
	"maxRetries\x12'\n" +
	"\x0ftimeout_seconds\x18\x06 \x01(\x05R\x0etimeoutSeconds\x12=\n" +
	"\fscheduled_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vscheduledAt\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x18\n" +
	"\apayload\x18\t \x01(\fR\apayload\"$\n" +
	"\vJobAccepted\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"y\n" +
	"\tJobResult\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x16\n" +
	"\x06output\x18\x03 \x01(\fR\x06output\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\":\n" +
	"\tCancelJob\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason2\\\n" +
	"\x11DispatcherService\x12G\n" +
	"\aConnect\x12\x18.jobqueue.v1.WorkerEvent\x1a\x1e.jobqueue.v1.DispatcherCommand(\x010\x01BHZFgithub.com/mohammad-khos/distributed-job-queue/shared/proto;jobqueuev1b\x06proto3"

var (
	file_job_proto_rawDescOnce sync.Once
	file_job_proto_rawDescData []byte
)

func file_job_proto_rawDescGZIP() []byte {
	file_job_proto_rawDescOnce.Do(func() {
		file_job_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_job_proto_rawDesc), len(file_job_proto_rawDesc)))
	})
	return file_job_proto_rawDescData
}

var file_job_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_job_proto_goTypes = []any{
	(*WorkerEvent)(nil),           // 0: jobqueue.v1.WorkerEvent
	(*DispatcherCommand)(nil),     // 1: jobqueue.v1.DispatcherCommand
	(*RegisterWorker)(nil),        // 2: jobqueue.v1.RegisterWorker
	(*Heartbeat)(nil),             // 3: jobqueue.v1.Heartbeat
	(*AssignJob)(nil),             // 4: jobqueue.v1.AssignJob
	(*JobAccepted)(nil),           // 5: jobqueue.v1.JobAccepted
	(*JobResult)(nil),             // 6: jobqueue.v1.JobResult
	(*CancelJob)(nil),             // 7: jobqueue.v1.CancelJob
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_job_proto_depIdxs = []int32{
	2, // 0: jobqueue.v1.WorkerEvent.register:type_name -> jobqueue.v1.RegisterWorker
	3, // 1: jobqueue.v1.WorkerEvent.heartbeat:type_name -> jobqueue.v1.Heartbeat
	5, // 2: jobqueue.v1.WorkerEvent.job_accepted:type_name -> jobqueue.v1.JobAccepted
	6, // 3: jobqueue.v1.WorkerEvent.job_result:type_name -> jobqueue.v1.JobResult
	4, // 4: jobqueue.v1.DispatcherCommand.assign_job:type_name -> jobqueue.v1.AssignJob
	7, // 5: jobqueue.v1.DispatcherCommand.cancel_job:type_name -> jobqueue.v1.CancelJob
	8, // 6: jobqueue.v1.AssignJob.scheduled_at:type_name -> google.protobuf.Timestamp
	8, // 7: jobqueue.v1.AssignJob.created_at:type_name -> google.protobuf.Timestamp
	0, // 8: jobqueue.v1.DispatcherService.Connect:input_type -> jobqueue.v1.WorkerEvent
	1, // 9: jobqueue.v1.DispatcherService.Connect:output_type -> jobqueue.v1.DispatcherCommand
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_job_proto_init() }
func file_job_proto_init() {
	if File_job_proto != nil {
		return
	}
	file_job_proto_msgTypes[0].OneofWrappers = []any{
		(*WorkerEvent_Register)(nil),
		(*WorkerEvent_Heartbeat)(nil),
		(*WorkerEvent_JobAccepted)(nil),
		(*WorkerEvent_JobResult)(nil),
	}
	file_job_proto_msgTypes[1].OneofWrappers = []any{
		(*DispatcherCommand_AssignJob)(nil),
		(*DispatcherCommand_CancelJob)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_job_proto_rawDesc), len(file_job_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_job_proto_goTypes,
		DependencyIndexes: file_job_proto_depIdxs,
		MessageInfos:      file_job_proto_msgTypes,
	}.Build()
	File_job_proto = out.File
	file_job_proto_goTypes = nil
	file_job_proto_depIdxs = nil
}
